policies:
  - name: "KerasPolicy"
    epochs: 500
    batch_size: 30
    augmentation_factor: 50
    validation_split: 0.2
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: "MemoizationPolicy"
    max_history: 4